### ISSUE TITLE
action is broken

### ISSUE THREAD

**Issue by vasiliy-t** [tarantool/setup-tarantool#20]
runs os ubuntu-latest

```yaml
name: Install tarantool
uses: tarantool/setup-tarantool@v1
with:
  tarantool-version: "2.8"
```

results in error

![telegram-cloud-photo-size-2-5305737920575027596-y](https://user-images.githubusercontent.com/4940266/145673759-a3cb2688-debc-416d-860c-f2aed55be264.jpg)
