### ISSUE TITLE
Unable to run the action inside docker

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/setup-tarantool#44]
I have a job set up as follows (github public runner):
```yaml
    runs-on: ubuntu-20.04
```
And then a step (you may take a look at the workflow file [here](https://github.com/tarantool/vshard/blob/686bde3fc29410ce6ebc22f8a5e499eaa8e4c984/.github/workflows/fast_testing.yml#L42-L46) ):
```yaml
      - name: Install tarantool ${{ matrix.tarantool }}
        if: startsWith(matrix.tarantool, 'release') != true
        uses: tarantool/setup-tarantool@v2
        with:
          tarantool-version: ${{ matrix.tarantool }}
```
The workflow passes fine, but if I change `runs-on` to:
```yaml
    runs-on: ubuntu-20.04-self-hosted                                            
    container:                                                                   
      image: docker.io/tarantool/testing:ubuntu-focal
```
or
```yaml
    runs-on: ubuntu-20.04-self-hosted                                            
    container:                                                                   
      image: ubuntu:20.04
```
The job starts failing like this:
```
Caching APT packages: build-essential, cmake, cmake-data, dpkg-dev, fakeroot, g++, g++-9, libalgorithm-diff-perl, libalgorithm-diff-xs-perl, libalgorithm-merge-perl, libarchive13:amd64, libcurl4:amd64, libdpkg-perl, libfakeroot:amd64, libfile-fcntllock-perl, libicu66:amd64, libjsoncpp1:amd64, liblocale-gettext-perl, librhash0:amd64, libstdc++-9-dev:amd64, libunwind8:amd64, libuv1:amd64, libxml2:amd64, make, tarantool, tarantool-common, tarantool-dev
Error: ENOENT: no such file or directory, stat '/usr/share/doc/build-essential/AUTHORS'
```

The problem is described in https://github.com/tarantool/setup-tarantool/pull/41#discussion_r1273641890 and should be fixed by #41
