### ISSUE TITLE
setup-tarantool fails on ubuntu-jammy docker image

### ISSUE THREAD

**Issue by mkokryashkin** [tarantool/setup-tarantool#59]
Having the following workflow:
```
jobs:
  test:
    container:
      image: docker.io/tarantool/testing:ubuntu-jammy
      # Mount /dev to the container to be able to mount a disk image inside it
      # for successful run of the .github/actions/environment action.
      volumes:
        - /dev:/dev
      # Our testing expects that the init process (PID 1) will
      # reap orphan processes. At least the following test leans
      # on it: app-tap/gh-4983-tnt-e-assert-false-hangs.test.lua.
      # Add extra privileges to the container for successful run
      # of the .github/actions/environment action.
      options: '--init --privileged'
      
    strategy:
      fail-fast: false
      matrix:
        tarantool: ['2.11']
    runs-on: [ self-hosted, ubuntu-20.04-self-hosted ]
    steps:
      - name: Get sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'recursive'
          
      - uses: tarantool/setup-tarantool@v2
        with:
          tarantool-version: ${{ matrix.tarantool }}
```

setup-tarantool fails with the following error:
```
/usr/bin/sudo apt-get install -y tarantool=2.11.4.g8cebbf2cad-1* tarantool-dev=2.11.4.g8cebbf2cad-1*
  Reading package lists...
  Building dependency tree...
  Reading state information...
  The following additional packages will be installed:
    tarantool-common
  Recommended packages:
    tt
  The following NEW packages will be installed:
    tarantool tarantool-common tarantool-dev
  0 upgraded, 3 newly installed, 0 to remove and 70 not upgraded.
  Need to get 13.1 MB of archives.
  After this operation, 38.4 MB of additional disk space will be used.
  Get:1 https://hb.bizmrg.com/tarantool_repo/release/series-2/ubuntu jammy/main all tarantool-common all 2.11.4.g8cebbf2cad-1 [43.6 kB]
  Get:2 https://hb.bizmrg.com/tarantool_repo/release/series-2/ubuntu jammy/main amd64 tarantool amd64 2.11.4.g8cebbf2cad-1 [13.0 MB]
  Get:3 https://hb.bizmrg.com/tarantool_repo/release/series-2/ubuntu jammy/main amd64 tarantool-dev amd64 2.11.4.g8cebbf2cad-1 [100 kB]
  debconf: delaying package configuration, since apt-utils is not installed
  Fetched 13.1 MB in 1s (14.3 MB/s)
  Selecting previously unselected package tarantool-common.
  (Reading database ... 
  (Reading database ... 5%
  (Reading database ... 10%
  (Reading database ... 15%
  (Reading database ... 20%
  (Reading database ... 25%
  (Reading database ... 30%
  (Reading database ... 35%
  (Reading database ... 40%
  (Reading database ... 45%
  (Reading database ... [50](https://github.com/tarantool/tarantool-wasm/actions/runs/10809470041/job/29985026288#step:4:55)%
  (Reading database ... 55%
  (Reading database ... 60%
  (Reading database ... 65%
  (Reading database ... 70%
  (Reading database ... 75%
  (Reading database ... 80%
  (Reading database ... 85%
  (Reading database ... 90%
  (Reading database ... 95%
  (Reading database ... 100%
  (Reading database ... 38727 files and directories currently installed.)
  Preparing to unpack .../tarantool-common_2.11.4.g8cebbf2cad-1_all.deb ...
  Unpacking tarantool-common (2.11.4.g8cebbf2cad-1) ...
  Selecting previously unselected package tarantool.
  Preparing to unpack .../tarantool_2.11.4.g8cebbf2cad-1_amd64.deb ...
  Unpacking tarantool (2.11.4.g8cebbf2cad-1) ...
  Selecting previously unselected package tarantool-dev.
  Preparing to unpack .../tarantool-dev_2.11.4.g8cebbf2cad-1_amd[64](https://github.com/tarantool/tarantool-wasm/actions/runs/10809470041/job/29985026288#step:4:69).deb ...
  Unpacking tarantool-dev (2.11.4.g8cebbf2cad-1) ...
  Setting up tarantool-common (2.11.4.g8cebbf2cad-1) ...
  Created symlink /etc/systemd/system/multi-user.target.wants/tarantool.service → /lib/systemd/system/tarantool.service.
  invoke-rc.d: could not determine current runlevel
  invoke-rc.d: policy-rc.d denied execution of start.
  Setting up tarantool (2.11.4.g8cebbf2cad-1) ...
  Setting up tarantool-dev (2.11.4.g8cebbf2cad-1) ...
Caching APT packages: tarantool, tarantool-common, tarantool-dev
Error: ENOENT: no such file or directory, stat '/usr/share/doc/tarantool/AUTHORS'
/usr/bin/tarantool --version
Tarantool 2.11.4-0-g8cebbf2cad
Target: Linux-x[86](https://github.com/tarantool/tarantool-wasm/actions/runs/10809470041/job/29985026288#step:4:91)_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=TRUE
Compiler: GNU-11.2.0
C_FLAGS:-g -O2 -ffile-prefix-map=/build/tarantool-2.11.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/build/tarantool-2.11.4=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu[89](https://github.com/tarantool/tarantool-wasm/actions/runs/10809470041/job/29985026288#step:4:94)-inline -Wno-cast-function-type
CXX_FLAGS:-g -O2 -ffile-prefix-map=/build/tarantool-2.11.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/build/tarantool-2.11.4=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```
